[package]
name = "haneru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
askama = "0.12.1"
askama_axum = "0.3.0"
async_cell = "0.2.2"
axum = "0.6.20"
futures = "0.3.28"
httparse = "1.8.0"
hyper = { version = "0.14.27", features = ["full"] }
hyper-rustls = "0.24.1"
moka = { version = "0.12.1", features = ["sync"] }
once_cell = "1.18.0"
rcgen = { version = "0.11.3", features = ["x509-parser"] }
rustls = "0.21.7"
rustls-pemfile = "1.0.3"
tokio = { version = "1.33.0", features = ["full"] }
tokio-rustls = "0.24.1"
tower-http = { version = "0.4.4", features = ["fs"] }
webpki-roots = "0.25.2"
